### ISSUE TITLE
 Module is not displayed

### ISSUE THREAD

**Issue by ghost** [lavolp3/MMM-Tasmota#1]
https://forum.magicmirror.builders/topic/13056/gosund-sp111/14

```
pi@raspberrypi:~/MagicMirror $ npm start dev

 magicmirror@2.11.0 start /home/pi/MagicMirror
DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-06-23 15:39:46.245] [LOG]    Starting MagicMirror: v2.11.0
[2020-06-23 15:39:46.258] [LOG]    Loading config ...
[2020-06-23 15:39:46.266] [LOG]    Loading module helpers ...
[2020-06-23 15:39:46.303] [LOG]    Initializing new module helper ...
[2020-06-23 15:39:46.304] [LOG]    Module helper loaded: MMM-Admin-Interface
[2020-06-23 15:39:46.307] [LOG]    No helper found for module: alert.
[2020-06-23 15:39:46.381] [LOG]    Initializing new module helper ...
[2020-06-23 15:39:46.383] [LOG]    Module helper loaded: updatenotification
[2020-06-23 15:39:46.384] [LOG]    No helper found for module: clock.
[2020-06-23 15:39:47.041] [LOG]    Initializing new module helper ...
[2020-06-23 15:39:47.042] [LOG]    Module helper loaded: calendar
[2020-06-23 15:39:47.043] [LOG]    No helper found for module: currentweather.
[2020-06-23 15:39:47.044] [LOG]    No helper found for module: weatherforecast.
[2020-06-23 15:39:47.045] [LOG]    No helper found for module: MMM-WiFiPassword.
[2020-06-23 15:39:47.048] [LOG]    Initializing new module helper ...
[2020-06-23 15:39:47.049] [LOG]    Module helper loaded: MMM-BurnIn
[2020-06-23 15:39:47.052] [LOG]    Initializing new module helper ...
[2020-06-23 15:39:47.053] [LOG]    Module helper loaded: MMM-COVID19
[2020-06-23 15:39:47.289] [LOG]    Initializing new module helper ...
[2020-06-23 15:39:47.290] [LOG]    Module helper loaded: MMM-Tasmota
[2020-06-23 15:39:47.291] [LOG]    All module helpers loaded.
[2020-06-23 15:39:47.463] [LOG]    Starting server on port 8080 ...
[2020-06-23 15:39:47.481] [INFO]   You're using a full whitelist configuration t                                                     o allow for all IPs
[2020-06-23 15:39:47.496] [LOG]    Server started ...
[2020-06-23 15:39:47.499] [LOG]    Connecting socket for: MMM-Admin-Interface
[2020-06-23 15:39:47.501] [LOG]    Starting node helper for: MMM-Admin-Interface
[2020-06-23 15:39:47.623] [LOG]    Connecting socket for: updatenotification
[2020-06-23 15:39:47.625] [LOG]    Connecting socket for: calendar
[2020-06-23 15:39:47.627] [LOG]    Starting node helper for: calendar
[2020-06-23 15:39:47.628] [LOG]    Connecting socket for: MMM-BurnIn
[2020-06-23 15:39:47.630] [LOG]    Connecting socket for: MMM-COVID19
[2020-06-23 15:39:47.631] [LOG]    Starting node helper for: MMM-COVID19
[2020-06-23 15:39:47.633] [LOG]    Connecting socket for: MMM-Tasmota
[2020-06-23 15:39:47.640] [LOG]    Sockets connected & modules started ...
[2020-06-23 15:39:47.764] [LOG]    Launching application.
[2020-06-23 15:39:53.722] [LOG]    Create new calendar fetcher for url: https://                                                     calendar.google.com/calendar/icalXXXXXXXbasic.ics - Interval: 300000
[2020-06-23 15:39:54.809] [LOG]    MMM-Tasmota: "Connected to host: http://local                                                     host:1883"
[2020-06-23 15:39:54.825] [LOG]    MMM-Tasmota: "Subscribing to topic: stat/Test                                                     dose/#"
[2020-06-23 15:39:54.867] [LOG]    MMM-Tasmota: "Subscribed to topic: stat/Testd                                                     ose/#"
[2020-06-23 15:40:47.027] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/RESULT: {\"POWER\":                             \"OFF\"}"
[2020-06-23 15:40:47.031] [LOG]    MMM-Tasmota: "Received data is not of known SENSOR or STATE format: {                             \"POWER\":\"OFF\"}"
[2020-06-23 15:40:47.034] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/POWER: OFF"
[2020-06-23 15:40:47.036] [LOG]    MMM-Tasmota: "Received data is not of known SENSOR or STATE format: O                             FF"
[2020-06-23 15:40:53.317] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/RESULT: {\"POWER\":                             \"ON\"}"
[2020-06-23 15:40:53.320] [LOG]    MMM-Tasmota: "Received data is not of known SENSOR or STATE format: {                             \"POWER\":\"ON\"}"
[2020-06-23 15:40:53.419] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/POWER: ON"
[2020-06-23 15:40:53.422] [LOG]    MMM-Tasmota: "Received data is not of known SENSOR or STATE format: O                             N"
```

![image](https://user-images.githubusercontent.com/65677882/85411177-4cec4400-b568-11ea-9516-d5377df485fb.png)

In MQTT.fx and in the console of device., i can see the pub topics with all the Data. Actually i have a TelePeriod of 10 seconds for testing.

I looked in my MQTT.fx and i get SENSOR-Data and STATE-Data in topic tele/Testdose/# only. in the subscribed topic from MMM-Tasmota i get POWER and RESULT but there isn´t SENSOR or STATE.

**Comment by lavolp3** [comment]
I think I understand what is happening here.
The messages I receive are from `stat/#topic#/LOGGING` , this logging level needs to be enabled via the logging config.
In the "Configure Logging" part, my mqtt log level is 2 ("info")
![image](https://user-images.githubusercontent.com/20084205/85457019-d834fc00-b59f-11ea-9010-26c2f9bf4306.png)

Can you please check?
I don't know if there's another/better way. I'm quite new to MQTT.

**Comment by ghost** [comment]
i have change it and now there is a little bit more, but i cant see the module displayed.

`pi@raspberrypi:~/MagicMirror $ pm2 stop all
[PM2] Applying action stopProcessId on app [all](ids: 0)
[PM2] [MagicMirror](0) ✓
┌─────┬────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name           │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ MagicMirror    │ default     │ 2.11.0  │ fork    │ 0        │ 0      │ 0    │ stopped   │ 0%       │ 0b       │ pi       │ disabled │
└─────┴────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-06-23 22:26:46.521] [LOG]    Starting MagicMirror: v2.11.0
[2020-06-23 22:26:46.535] [LOG]    Loading config ...
[2020-06-23 22:26:46.544] [LOG]    Loading module helpers ...
[2020-06-23 22:26:46.584] [LOG]    Initializing new module helper ...
[2020-06-23 22:26:46.585] [LOG]    Module helper loaded: MMM-Admin-Interface
[2020-06-23 22:26:46.588] [LOG]    No helper found for module: alert.
[2020-06-23 22:26:46.656] [LOG]    Initializing new module helper ...
[2020-06-23 22:26:46.657] [LOG]    Module helper loaded: updatenotification
[2020-06-23 22:26:46.658] [LOG]    No helper found for module: clock.
[2020-06-23 22:26:47.358] [LOG]    Initializing new module helper ...
[2020-06-23 22:26:47.359] [LOG]    Module helper loaded: calendar
[2020-06-23 22:26:47.360] [LOG]    No helper found for module: currentweather.
[2020-06-23 22:26:47.361] [LOG]    No helper found for module: weatherforecast.
[2020-06-23 22:26:47.363] [LOG]    No helper found for module: MMM-WiFiPassword.
[2020-06-23 22:26:47.366] [LOG]    Initializing new module helper ...
[2020-06-23 22:26:47.367] [LOG]    Module helper loaded: MMM-BurnIn
[2020-06-23 22:26:47.370] [LOG]    Initializing new module helper ...
[2020-06-23 22:26:47.372] [LOG]    Module helper loaded: MMM-COVID19
[2020-06-23 22:26:47.634] [LOG]    Initializing new module helper ...
[2020-06-23 22:26:47.635] [LOG]    Module helper loaded: MMM-Tasmota
[2020-06-23 22:26:47.636] [LOG]    All module helpers loaded.
[2020-06-23 22:26:47.831] [LOG]    Starting server on port 8080 ...
[2020-06-23 22:26:47.847] [INFO]   You're using a full whitelist configuration to allow for all IPs
[2020-06-23 22:26:47.860] [LOG]    Server started ...
[2020-06-23 22:26:47.862] [LOG]    Connecting socket for: MMM-Admin-Interface
[2020-06-23 22:26:47.864] [LOG]    Starting node helper for: MMM-Admin-Interface
[2020-06-23 22:26:47.999] [LOG]    Connecting socket for: updatenotification
[2020-06-23 22:26:48.001] [LOG]    Connecting socket for: calendar
[2020-06-23 22:26:48.002] [LOG]    Starting node helper for: calendar
[2020-06-23 22:26:48.003] [LOG]    Connecting socket for: MMM-BurnIn
[2020-06-23 22:26:48.005] [LOG]    Connecting socket for: MMM-COVID19
[2020-06-23 22:26:48.006] [LOG]    Starting node helper for: MMM-COVID19
[2020-06-23 22:26:48.007] [LOG]    Connecting socket for: MMM-Tasmota
[2020-06-23 22:26:48.014] [LOG]    Sockets connected & modules started ...
[2020-06-23 22:26:48.152] [LOG]    Launching application.
[2020-06-23 22:26:54.843] [LOG]    Create new calendar fetcher for url: https://calendar.google.com/calendar/icalXXXX Interval: 300000
[2020-06-23 22:26:56.085] [LOG]    MMM-Tasmota: "Connected to host: http://localhost:1883"
[2020-06-23 22:26:56.088] [LOG]    MMM-Tasmota: "Subscribing to topic: stat/Testdose/#"
[2020-06-23 22:26:56.132] [LOG]    MMM-Tasmota: "Subscribed to topic: stat/Testdose/#"
[2020-06-23 22:26:56.361] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/LOGGING: 21:26:55 MQT: tele/Testdose/STATE = {\"Time\":\"2020-06-23T21:26:55\",\"Uptime\":\"1T00:14:06\",\"UptimeSec\":87246,\"Heap\":26,\"SleepMode\":\"Dynamic\",\"Sleep\":50,\"LoadAvg\":19,\"MqttCount\":3,\"POWER\":\"OFF\",\"Wifi\":{\"AP\":2,\"SSId\":\"Helix 2,4GHz\",\"BSSId\":\"44:4E:6D:94:88:30\",\"Channel\":1,\"RSSI\":100,\"Signal\":-48,\"LinkCount\":1,\"Downtime\":\"0T00:00:03\"}}"
[2020-06-23 22:26:56.367] [LOG]    Whoops! There was an uncaught exception...
[2020-06-23 22:26:56.377] [ERROR]  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Class.parseData (/home/pi/MagicMirror/modules/MMM-Tasmota/node_helper.js:93:33)
    at MqttClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Tasmota/node_helper.js:79:18)
    at MqttClient.emit (events.js:200:13)
    at MqttClient._handlePublish (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:351:12)
    at work (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/readable-stream/lib/_stream_writable.js:417:5)
[2020-06-23 22:26:56.407] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-06-23 22:26:56.409] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

`

**Comment by lavolp3** [comment]
Ok I'm not sure what the problem is but I pushed some changes to the module.
You know the drill :-)
Oh, and thanks for being my beta tester! Much appreciated :-)

**Comment by ghost** [comment]
if you want we can make a session via teamviewer? maybe you can test it better?

`pi@raspberrypi:MagicMirror $ pm2 stop all
PM2] Applying action stopProcessId on app [all](ids: 0)
PM2] [MagicMirror](0) ✓
┌─────┬────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
id  │ name           │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching ─────┼────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
 0   │ MagicMirror    │ default     │ 2.11.0  │ fork    │ 0        │ 0      │ 0    │ stopped   │ 0%       │ 0b       │ pi       │ disabled │
└─────┴────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
pi@raspberrypi:~/MagicMirror $ cd modules/MMM-Tasmota
pi@raspberrypi:~/MagicMirror/modules/MMM-Tasmota $ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0
Entpacke Objekte: 100% (5/5), Fertig.
Von https://github.com/lavolp3/MMM-Tasmota
   99b4cc5..2456b2a  master     -> origin/master
Aktualisiere 99b4cc5..2456b2a
Fast-forward
 MMM-Tasmota.js   |  2 +-
 mmm-tasmota.njk  | 37 -------------------------------------
 node_helper.js   |  3 ++-
 tasmotadata.json |  2 +-
 4 files changed, 4 insertions(+), 40 deletions(-)
 delete mode 100755 mmm-tasmota.njk
pi@raspberrypi:~/MagicMirror/modules/MMM-Tasmota $ cd ..
pi@raspberrypi:~/MagicMirror/modules $ cd ..
pi@raspberrypi:~/MagicMirror $ npm start dev

magicmirror@2.11.0 start /home/pi/MagicMirror
 DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-06-23 22:47:23.723] [LOG]    Starting MagicMirror: v2.11.0
[2020-06-23 22:47:23.750] [LOG]    Loading config ...
[2020-06-23 22:47:23.759] [LOG]    Loading module helpers ...
[2020-06-23 22:47:23.811] [LOG]    Initializing new module helper ...
[2020-06-23 22:47:23.814] [LOG]    Module helper loaded: MMM-Admin-Interface
[2020-06-23 22:47:23.820] [LOG]    No helper found for module: alert.
[2020-06-23 22:47:23.912] [LOG]    Initializing new module helper ...
[2020-06-23 22:47:23.914] [LOG]    Module helper loaded: updatenotification
[2020-06-23 22:47:23.918] [LOG]    No helper found for module: clock.
[2020-06-23 22:47:24.906] [LOG]    Initializing new module helper ...
[2020-06-23 22:47:24.907] [LOG]    Module helper loaded: calendar
[2020-06-23 22:47:24.911] [LOG]    No helper found for module: currentweather.
[2020-06-23 22:47:24.915] [LOG]    No helper found for module: weatherforecast.
[2020-06-23 22:47:24.919] [LOG]    No helper found for module: MMM-WiFiPassword.
[2020-06-23 22:47:24.925] [LOG]    Initializing new module helper ...
[2020-06-23 22:47:24.928] [LOG]    Module helper loaded: MMM-BurnIn
[2020-06-23 22:47:24.933] [LOG]    Initializing new module helper ...
[2020-06-23 22:47:24.934] [LOG]    Module helper loaded: MMM-COVID19
[2020-06-23 22:47:25.315] [LOG]    Initializing new module helper ...
[2020-06-23 22:47:25.316] [LOG]    Module helper loaded: MMM-Tasmota
[2020-06-23 22:47:25.317] [LOG]    All module helpers loaded.
[2020-06-23 22:47:25.598] [LOG]    Starting server on port 8080 ...
[2020-06-23 22:47:25.627] [INFO]   You're using a full whitelist configuration to allow for all IPs
[2020-06-23 22:47:25.655] [LOG]    Server started ...
[2020-06-23 22:47:25.659] [LOG]    Connecting socket for: MMM-Admin-Interface
[2020-06-23 22:47:25.661] [LOG]    Starting node helper for: MMM-Admin-Interface
[2020-06-23 22:47:25.863] [LOG]    Connecting socket for: updatenotification
[2020-06-23 22:47:25.866] [LOG]    Connecting socket for: calendar
[2020-06-23 22:47:25.867] [LOG]    Starting node helper for: calendar
[2020-06-23 22:47:25.868] [LOG]    Connecting socket for: MMM-BurnIn
[2020-06-23 22:47:25.870] [LOG]    Connecting socket for: MMM-COVID19
[2020-06-23 22:47:25.871] [LOG]    Starting node helper for: MMM-COVID19
[2020-06-23 22:47:25.872] [LOG]    Connecting socket for: MMM-Tasmota
[2020-06-23 22:47:25.879] [LOG]    Sockets connected & modules started ...
[2020-06-23 22:47:26.105] [LOG]    Launching application.
[2020-06-23 22:47:33.261] [LOG]    Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/
[2020-06-23 22:47:34.686] [LOG]    MMM-Tasmota: "Connected to host: http://localhost:1883"
[2020-06-23 22:47:34.712] [LOG]    MMM-Tasmota: "Subscribing to topic: stat/Testdose/#"
[2020-06-23 22:47:34.763] [LOG]    MMM-Tasmota: "Subscribed to topic: stat/Testdose/#"
[2020-06-23 22:47:36.310] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/LOGGING: 21:47:36 MQT: tele/Testdose/STATE = {\"Time\":\"2020-06-23T21:47:36\",\"Uptime\":\"1T00:34:47\",\"UptimeSec\":88487,\"Heap\":26,\"SleepMode\":\"Dynamic\",\"Sleep\":50,\"LoadAvg\":19,\"MqttCount\":3,\"POWER\":\"ON\",\"Wifi\":{\"AP\":2,\"SSId\":\"Helix 2,4GHz\",\"BSSId\":\"44:4E:6D:94:88:30\",\"Channel\":1,\"RSSI\":100,\"Signal\":-48,\"LinkCount\":1,\"Downtime\":\"0T00:00:03\"}}"
[2020-06-23 22:47:36.313] [LOG]    MMM-Tasmota: "Topic: tele/Testdose/STATE, json: {\"Time\":\"2020-06-23T21:47:36\",\"Uptime\":\"1T00:34:47\",\"UptimeSec\":88487,\"Heap\":26,\"SleepMode\":\"Dynamic\",\"Sleep\":50,\"LoadAvg\":19,\"MqttCount\":3,\"POWER\":\"ON\",\"Wifi\":{\"AP\":2,\"SSId\":\"Helix"
[2020-06-23 22:47:36.324] [LOG]    Whoops! There was an uncaught exception...
[2020-06-23 22:47:36.335] [ERROR]  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Class.parseData (/home/pi/MagicMirror/modules/MMM-Tasmota/node_helper.js:94:33)
    at MqttClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Tasmota/node_helper.js:79:18)
    at MqttClient.emit (events.js:200:13)
    at MqttClient._handlePublish (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:351:12)
    at work (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/readable-stream/lib/_stream_writable.js:417:5)
[2020-06-23 22:47:36.368] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-06-23 22:47:36.369] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
`

**Comment by lavolp3** [comment]
well that's interesting. Your ssid name has a space that conflicts with the way the message is being processed (split into an array by spaces)
I will have to find another way. Will get back to you

**Comment by ghost** [comment]
Now i can see the module. But there is no Data at the moment. 

![Unbenannt](https://user-images.githubusercontent.com/65677882/85536771-af4e4e80-b613-11ea-992e-bb4b3fee4d57.jpg)

If i toggle the Plug

`[2020-06-24 12:14:06.250] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/RESULT: {\"POWER\":\"OFF\"}"
[2020-06-24 12:14:06.252] [LOG]    MMM-Tasmota: "Topic: undefined, json: "
[2020-06-24 12:14:06.253] [LOG]    MMM-Tasmota: "Received data is not of known SENSOR or STATE format: {\"POWER\":\"OFF\"}"
[2020-06-24 12:14:06.257] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/LOGGING: 12:14:05 MQT: stat/Testdose/RESULT = {\"POWER\":\"OFF\"}"
[2020-06-24 12:14:06.258] [LOG]    MMM-Tasmota: "Topic: stat/Testdose/RESULT, json: {\"POWER\":\"OFF\"}"
[2020-06-24 12:14:06.259] [LOG]    MMM-Tasmota: "Processed JSON data: {\"POWER\":\"OFF\"}"
[2020-06-24 12:14:06.261] [LOG]    MMM-Tasmota: "Received data is not of SENSOR or STATE format: 12:14:05 MQT: stat/Testdose/RESULT = {\"POWER\":\"OFF\"}"
[2020-06-24 12:14:06.264] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/POWER: OFF"
[2020-06-24 12:14:06.265] [LOG]    MMM-Tasmota: "Topic: undefined, json: "
[2020-06-24 12:14:06.266] [LOG]    MMM-Tasmota: "Received data is not of known SENSOR or STATE format: OFF"
[2020-06-24 12:14:06.268] [LOG]    MMM-Tasmota: "Received message from stat/Testdose/LOGGING: 12:14:05 MQT: stat/Testdose/POWER = OFF"
[2020-06-24 12:14:06.269] [LOG]    MMM-Tasmota: "Topic: stat/Testdose/POWER, json: OFF"
[2020-06-24 12:14:06.273] [LOG]    Whoops! There was an uncaught exception...
[2020-06-24 12:14:06.275] [ERROR]  SyntaxError: Unexpected token O in JSON at position 0
    at JSON.parse (<anonymous>)
    at Class.parseData (/home/pi/MagicMirror/modules/MMM-Tasmota/node_helper.js:95:33)
    at MqttClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Tasmota/node_helper.js:79:18)
    at MqttClient.emit (events.js:200:13)
    at MqttClient._handlePublish (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:351:12)
    at work (/home/pi/MagicMirror/modules/MMM-Tasmota/node_modules/mqtt/lib/client.js:283:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
[2020-06-24 12:14:06.280] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-06-24 12:14:06.281] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

`

**Comment by lavolp3** [comment]
I'm in the middle of updating. Wait for the next update. Most probably tonight.

**Comment by lavolp3** [comment]
I have pushed a bigger update. Please try out again.
Thanks!

**Comment by ghost** [comment]
Now i can see the values, but the graph don´t move. Or its my fault? I thought the graph updates itself every minute or isn't it?

After 15 minutes the same picture. TelePeriod in device is 10 seconds, And UpdateIntervall i have changed after 6 minutes to 10 seconds too.

![DSC_0060](https://user-images.githubusercontent.com/65677882/85835490-750cba80-b795-11ea-8e86-83dbe5cf3afb.JPG)

**Comment by lavolp3** [comment]
Aaaaand another one. 
You found again a minor but important bug! Thanks!
Please try again!

**Comment by lavolp3** [comment]
please note the config offers you a `teleInterval` and `chartInterval` option for every device.
These are for calculation purposes only but might solve odd behaviour in the graph.
The amount of graph points is calculated by (Chartinterval*60*60 / teleInterval)

You can set option `teleInterval` to the one in your device config and `chartInterval` to your preference.
Have a look in the readme.

Additionally, I would advise to set your telemetry interval not to 10 seconds (only for testing purposes) but to at least 30 seconds. Don't know what the module does with 5 devices and 10 seconds teleInterval.

**Comment by lordhelix** [comment]
Perfect now this works fine with device. an other problem: I cant see the module, if i want more devices.

maybe my code is incorrect? The first code give me an error in config.js and with second code the module isn´t displayed

```
devices: [
            {
              topic: 'Testdose', name: 'dose', showPowerStats: true, teleInterval: '30', chartInterval: '1', chartColor: 'white'
            }
            {
              topic: 'Test2', name: 'test', showPowerStats: true, teleInterval: '30', chartInterval: '1', chartColor: 'white'
            }
        ],
```
and with comma between devices
```
devices: [
            {
              topic: 'Testdose', name: 'dose', showPowerStats: true, teleInterval: '30', chartInterval: '1', chartColor: 'white'
            },
            {
              topic: 'Test2', name: 'test', showPowerStats: true, teleInterval: '30', chartInterval: '1', chartColor: 'white'
            }
        ],
```

**Comment by ghost** [comment]
Perfect. Works fine for me now.
I thanks a lot. 

One more question. is it possible to calculate several parts?
I have 5 plugs in my bedroom. Can i see the calculated Values with the Headline Bedroom without every device? thats very interesting or me. Because i want to see every Room, not every Plug

**Comment by lavolp3** [comment]
Not yet. 
May be implemented, but I'm afraid that will complicate things considerably.
You would need a deeper topic that includes the room, like %prefix%/bedroom/plug1/%cmd%

Then I think I would be able to implement it by collecting all bedroom plugs into one object.
But I need to finish a few other modules first.
